---
title: "Examples: Assistments CV"
author: "Philip I. Pavlik Jr."
date: "2026-06-07"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Examples: Assistments CV}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup}
source("lkt-vignette-setup.R")
```

# Load Assistments 2012 skillbuilder

```{r load-assistments-2012}
val3 <- prepare_assistments_sample()
```

# Assistments data CV

```{r assistments-cv}
LLs <- numeric(0)
AUCs <- numeric(0)
R2s <- numeric(0)
RMSEs <- numeric(0)

val3$problem_id <- as.character(val3$problem_id)
for (i in 1:5) {
  print((1:5)[-i])

  val3$mean_correct <- NULL
  mean_data_not_i <- val3 %>%
    filter(fold != i) %>%
    group_by(problem_id) %>%
    summarise(mean_correct = mean(correct)) %>%
    ungroup()

  kmeans_result_not_i <- kmeans(mean_data_not_i$mean_correct, centers = 4)
  breaks_not_i <- c(
    min(mean_data_not_i$mean_correct),
    sort(kmeans_result_not_i$centers),
    max(mean_data_not_i$mean_correct)
  )

  val3 <- left_join(val3, mean_data_not_i, by = "problem_id")
  val3 <- val3 %>%
    mutate(
      difficuty_level = cut(
        mean_correct,
        breaks = breaks_not_i,
        labels = c("a", "b", "c", "d", "e"),
        include.lowest = TRUE
      )
    )
  val3 <- val3 %>%
    mutate(
      difficuty_level = if_else(
        is.na(difficuty_level),
        "c",
        as.character(difficuty_level)
      )
    )

  data.table::setDT(val3)
  val3[, difficuty_level := ifelse(.N <= 4, "c", difficuty_level),
       by = problem_id]

  modelob <- LKT(
    usefolds = (1:5)[-i],
    data = val3,
    interc = TRUE,
    fixedpars = c(.8, .94, .25),
    cost = 512,
    components = c("skill", "type", "skill", "difficuty_level"),
    features = c("propdec", "logitdec", "recency", "intercept")
  )

  pred <- as.vector(pmin(pmax(inv.logit(
    as.matrix(modelob$predictors %*% modelob$coefs)[, ]
  ), .00001), .99999)[modelob$newdata$fold %in% i])
  actual <- modelob$newdata$CF..ansbin.[modelob$newdata$fold %in% i]
  LLs[i] <- sum(log(ifelse(actual == 1, pred, 1 - pred)))
  AUCs[i] <- suppressMessages(pROC::auc(actual, pred)[1])
  print(AUCs[i])
  nullmodel <- glm(
    actual ~ 1,
    data = as.data.frame(rep(1, length(actual))),
    family = binomial(logit)
  )
  R2s[i] <- round(1 - LLs[i] / logLik(nullmodel)[1], 6)
  RMSEs[i] <- sqrt(mean((actual - pred)^2))
  print(R2s[i])
  print(RMSEs[i])
}

check_true("Assistments CV has five folds", length(AUCs) == 5 && length(R2s) == 5)
check_close("Assistments CV first AUC", AUCs[1], 0.6799578, tolerance = 5e-3)
check_close("Assistments CV first R2", R2s[1], -0.241313, tolerance = 5e-3)
```
