#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

SEXP C_lkt_online_simple_adaptive_eval(SEXP par_,
                                       SEXP y_,
                                       SEXP x_recency_,
                                       SEXP x_logsuc_,
                                       SEXP x_logitdec_,
                                       SEXP subject_start_,
                                       SEXP subject_end_,
                                       SEXP clip_epsilon_,
                                       SEXP denom_epsilon_,
                                       SEXP return_details_);
SEXP C_lkt_online_simple_adaptive_gradient(SEXP par_,
                                           SEXP y_,
                                           SEXP x_recency_,
                                           SEXP x_logsuc_,
                                           SEXP x_logitdec_,
                                           SEXP subject_start_,
                                           SEXP subject_end_,
                                           SEXP clip_epsilon_,
                                           SEXP denom_epsilon_);
SEXP C_lkt_online_simple_adaptive_value_gradient(SEXP par_,
                                                 SEXP y_,
                                                 SEXP x_recency_,
                                                 SEXP x_logsuc_,
                                                 SEXP x_logitdec_,
                                                 SEXP subject_start_,
                                                 SEXP subject_end_,
                                                 SEXP clip_epsilon_,
                                                 SEXP denom_epsilon_);
SEXP C_lkt_online_simple_adaptive_decay_eval(SEXP par_,
                                             SEXP y_,
                                             SEXP x_spacing_,
                                             SEXP x_logsuc_,
                                             SEXP x_logitdec_,
                                             SEXP subject_start_,
                                             SEXP subject_end_,
                                             SEXP recency_decay_start_,
                                             SEXP decay_lower_,
                                             SEXP decay_upper_,
                                             SEXP clip_epsilon_,
                                             SEXP denom_epsilon_,
                                             SEXP return_details_);
SEXP C_lkt_online_adaptive_beta_eval(SEXP alpha_,
                                     SEXP y_,
                                     SEXP eta_base_,
                                     SEXP x_beta_,
                                     SEXP beta_start_,
                                     SEXP subject_start_,
                                     SEXP subject_end_,
                                     SEXP clip_epsilon_,
                                     SEXP denom_epsilon_,
                                     SEXP return_details_);
SEXP C_lkt_online_adaptive_recency_decay_eval(SEXP alpha_,
                                              SEXP y_,
                                              SEXP eta_base_,
                                              SEXP x_beta_,
                                              SEXP beta_start_,
                                              SEXP x_spacing_,
                                              SEXP x_recency_original_,
                                              SEXP recency_coefficient_,
                                              SEXP subject_start_,
                                              SEXP subject_end_,
                                              SEXP recency_decay_start_,
                                              SEXP decay_lower_,
                                              SEXP decay_upper_,
                                              SEXP clip_epsilon_,
                                              SEXP denom_epsilon_,
                                              SEXP return_details_);
SEXP C_lkt_online_adaptive_feature_decay_eval(SEXP alpha_,
                                              SEXP y_,
                                              SEXP eta_base_,
                                              SEXP x_beta_,
                                              SEXP beta_start_,
                                              SEXP nonlinear_type_,
                                              SEXP nonlinear_aux_,
                                              SEXP nonlinear_original_,
                                              SEXP nonlinear_coefficient_,
                                              SEXP nonlinear_start_,
                                              SEXP subject_start_,
                                              SEXP subject_end_,
                                              SEXP nonlinear_lower_,
                                              SEXP nonlinear_upper_,
                                              SEXP clip_epsilon_,
                                              SEXP denom_epsilon_,
                                              SEXP return_details_);
SEXP C_lkt_online_adaptive_feature_group_eval(SEXP alpha_,
                                              SEXP y_,
                                              SEXP eta_base_,
                                              SEXP x_beta_,
                                              SEXP beta_start_,
                                              SEXP group_type_,
                                              SEXP group_aux_,
                                              SEXP group_original_,
                                              SEXP group_coefficient_,
                                              SEXP group_start_,
                                              SEXP group_active_,
                                              SEXP subject_start_,
                                              SEXP subject_end_,
                                              SEXP nonlinear_lower_,
                                              SEXP nonlinear_upper_,
                                              SEXP clip_epsilon_,
                                              SEXP denom_epsilon_,
                                              SEXP return_details_);

static const R_CallMethodDef CallEntries[] = {
  {"C_lkt_online_simple_adaptive_eval",
   (DL_FUNC) &C_lkt_online_simple_adaptive_eval, 10},
  {"C_lkt_online_simple_adaptive_gradient",
   (DL_FUNC) &C_lkt_online_simple_adaptive_gradient, 9},
  {"C_lkt_online_simple_adaptive_value_gradient",
   (DL_FUNC) &C_lkt_online_simple_adaptive_value_gradient, 9},
  {"C_lkt_online_simple_adaptive_decay_eval",
   (DL_FUNC) &C_lkt_online_simple_adaptive_decay_eval, 13},
  {"C_lkt_online_adaptive_beta_eval",
   (DL_FUNC) &C_lkt_online_adaptive_beta_eval, 10},
  {"C_lkt_online_adaptive_recency_decay_eval",
   (DL_FUNC) &C_lkt_online_adaptive_recency_decay_eval, 16},
  {"C_lkt_online_adaptive_feature_decay_eval",
   (DL_FUNC) &C_lkt_online_adaptive_feature_decay_eval, 17},
  {"C_lkt_online_adaptive_feature_group_eval",
   (DL_FUNC) &C_lkt_online_adaptive_feature_group_eval, 18},
  {NULL, NULL, 0}
};

void R_init_LKT(DllInfo *dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
